#ifndef VTEST_PROTOCOL_H
#define VTEST_PROTOCOL_H

#include <cstdint>

/**
 * vtest Protocol Commands
 *
 * Reference: virglrenderer/vtest/vtest_protocol.h
 */
enum VTestCommand {
    VCMD_GET_CAPS = 1,
    VCMD_RESOURCE_CREATE = 2,
    VCMD_RESOURCE_UNREF = 3,
    VCMD_TRANSFER_GET = 4,
    VCMD_TRANSFER_PUT = 5,
    VCMD_SUBMIT_CMD = 6,
    VCMD_RESOURCE_BUSY_WAIT = 7,
    VCMD_CREATE_RENDERER = 8,
    VCMD_GET_CAPS2 = 9,
    VCMD_PING_PROTOCOL_VERSION = 10,
    VCMD_PROTOCOL_VERSION = 11,
    VCMD_RESOURCE_CREATE2 = 12,
    VCMD_TRANSFER_GET2 = 13,
    VCMD_TRANSFER_PUT2 = 14,
    VCMD_GET_PARAM = 15,
    VCMD_GET_CAPSET = 16,
    VCMD_CONTEXT_INIT = 17,
    VCMD_RESOURCE_CREATE_BLOB = 18,
    VCMD_SYNC_CREATE = 19,
    VCMD_SYNC_UNREF = 20,
    VCMD_SYNC_READ = 21,
    VCMD_SYNC_WRITE = 22,
    VCMD_SYNC_WAIT = 23,
    VCMD_SUBMIT_CMD2 = 24,
};

/**
 * Capset IDs
 */
#define VIRTGPU_DRM_CAPSET_VIRGL   1
#define VIRTGPU_DRM_CAPSET_VIRGL2  2
#define VIRTGPU_DRM_CAPSET_VENUS   3

/**
 * Blob types
 */
#define VIRGL_RENDERER_BLOB_MEM_GUEST        0x0001
#define VIRGL_RENDERER_BLOB_MEM_HOST3D       0x0002
#define VIRGL_RENDERER_BLOB_MEM_HOST3D_GUEST 0x0003

/**
 * Blob flags
 */
#define VIRGL_RENDERER_BLOB_FLAG_USE_MAPPABLE     0x0001
#define VIRGL_RENDERER_BLOB_FLAG_USE_SHAREABLE    0x0002
#define VIRGL_RENDERER_BLOB_FLAG_USE_CROSS_DEVICE 0x0004

#endif // VTEST_PROTOCOL_H
